Added endpoints for events table
ctc-uci/lpa pull request #28
Opened 2024-12-15 22:51 UTC by antsuh1028

## Description
Added the api endpoints
## Screenshots/Media
![image](https://github.com/user-attachments/assets/75e4adec-59d2-455a-89b4-076281cb614f)

## Issues
Closes #21

2025-01-09 21:27 UTC, jessieh9 requested changes
Hey @antsuh1028 @dnarimot, there are a few edits that need to be made. We'll go over this at the sprint meeting tomorrow so don't worry about it yet!

Double-check [this file](https://www.figma.com/board/IGhSX7KS7MgUAtdBqPT3mM/%5BLPA%5D-1C.-Database-Model?node-id=4008-41&t=KBJC0nAjareGL7W8-1) for the input and output data for each request.

Todo:
- [ ] Remember to export the router for use in app.ts and that way we can have the endpoints of the router in app.ts already start with '/events' and then in events.js the endpoint can just be /
    - You can also access our database and test the routes on Postman. We can immediately see something is off when we start the server and there are errors on Postman.

2025-01-10 06:04 UTC, antsuh1028 commented
Okay, I got the changes to work, tested in Postman, thank you.

2025-01-10 06:38 UTC, theNatePi commented
Thank you! Will take another look this weekend.

2025-01-13 23:57 UTC, jessieh9 commented
TL's To-do

- [ ] Import event router into the app.js
- [ ] Use coalesce for PUT instead of 2 DB requests

2025-01-14 21:40 UTC, jessieh9 submitted a review, later dismissed

2025-01-14 21:49 UTC, merged